export const AUTH_SING_UP_SUCESS = "AUTH_SING_UP_SUCESS";
export const AUTH_SING_UP_START = "AUTH_SING_UP_START";
export const AUTH_SING_UP_FAIL = "AUTH_SING_UP_FAIL";

export const AUTH_SING_IN_SUCESS = "AUTH_SING_IN_SUCESS";
export const AUTH_SING_IN_START = "AUTH_SING_IN_START";
export const AUTH_SING_IN_FAIL = "AUTH_SING_IN_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";

export const USER_DETAIL_DATABASE_FAIL = "USER_DETAIL_DATABASE_FAIL";
export const USER_DETAIL_DATABASE_SUCESS = "USER_DETAIL_DATABASE_SUCESS";
export const USER_DETAIL_DATABASE_START = "USER_DETAIL_DATABASE_START";

export const USER_DETAIL_GET_DATABASE_FAIL = "USER_DETAIL_GET_DATABASE_FAIL";
export const USER_DETAIL_GET_DATABASE_SUCESS =
  "USER_DETAIL_GET_DATABASE_SUCESS";
export const USER_DETAIL_GET_DATABASE_START = "USER_DETAIL_GET_DATABASE_START";
